pub const NEUTRAL: [&str; 59] = [
    "is a capable and constantly improving software engineer.",
    "writes code that is clear, maintainable, and purposeful.",
    "learns quickly from bugs and failures.",
    "is patient when solving complex problems.",
    "can break down large tasks into manageable steps.",
    "is comfortable asking questions and seeking clarification.",
    "continuously improves their skills through practice and curiosity.",
    "is allowed to not know everything; they can always learn.",
    "can understand any system given enough time.",
    "is resilient when facing challenging technical issues.",
    "{username}’s value is not defined by how many lines of code they write.",
    "writes tests that provide confidence in their code.",
    "communicates clearly with teammates and stakeholders.",
    "can learn new languages, frameworks, and tools.",
    "is capable of understanding complex architectures.",
    "contributes positively to the team and the codebase.",
    "improves with every code review they participate in.",
    "handles constructive feedback professionally and calmly.",
    "is capable of designing robust and scalable solutions.",
    "manages time and energy effectively.",
    "is allowed to take breaks to protect focus and wellbeing.",
    "can return to difficult problems with fresh perspective.",
    "is not defined by a single bug or production incident.",
    "debugs systematically and calmly under pressure.",
    "embraces refactoring as a path to better software.",
    "writes documentation that helps others understand their work.",
    "can balance perfectionism with practicality.",
    "becomes more accurate at estimating work over time.",
    "can say no to unrealistic expectations respectfully.",
    "collaborates and shares knowledge generously.",
    "is constantly growing as an engineer and as a person.",
    "trusts their ability to learn unfamiliar codebases.",
    "sees patterns and abstractions that simplify complexity.",
    "is allowed to change their mind when learning new information.",
    "recognizes that good software is a continuous process.",
    "handles legacy code with patience and strategy.",
    "improves problem‑solving skills every day.",
    "navigates ambiguity and incomplete requirements.",
    "is capable of making thoughtful technical decisions.",
    "can admit when they are wrong and adjust quickly.",
    "is disciplined about writing secure and safe code.",
    "prioritizes tasks that create the most value.",
    "is mindful of performance without premature optimization.",
    "separates self‑worth from code flaws.",
    "is capable of mentoring and supporting other developers.",
    "learns from engineers who are more experienced.",
    "shares knowledge with those who are less experienced.",
    "adapts well to changing technologies and environments.",
    "stays calm when production issues arise.",
    "embraces code reviews as opportunities, not judgments.",
    "designs code that is easy to change.",
    "is learning to name things clearly and meaningfully.",
    "is capable of reading and understanding documentation.",
    "accepts that sometimes the simplest solution is best.",
    "balances technical excellence with business needs.",
    "is allowed time to deeply understand a problem.",
    "communicates technical tradeoffs clearly.",
    "builds a strong engineering mindset day by day.",
    "is proud of the progress they have made as a software engineer.",
];

pub const SENIOR: [&str; 40] = [
    "leads by example through thoughtful design and calm decision‑making.",
    "turns ambiguous requirements into clear technical direction.",
    "multiplies impact by enabling others to do their best work.",
    "balances short‑term delivery with long‑term code health.",
    "makes tradeoffs transparently and explains them clearly.",
    "mentors others with patience, empathy, and practical guidance.",
    "creates an environment where teammates feel safe to ask questions.",
    "is trusted to own complex systems end to end.",
    "anticipates risks early and acts before they become crises.",
    "drives architectural discussions with clarity and humility.",
    "knows when to simplify and when to invest in abstraction.",
    "champions testing, observability, and reliability in every project.",
    "helps align technical decisions with business goals.",
    "stays calm and methodical during production incidents.",
    "helps teams focus on what truly matters right now.",
    "recognizes and removes friction in the development process.",
    "advocates for sustainable pace and healthy engineering culture.",
    "can explain complex concepts in simple, accessible language.",
    "gives feedback that is direct, kind, and actionable.",
    "designs systems that are resilient to change over time.",
    "is intentional about code quality and pragmatism.",
    "delegates effectively, creating growth opportunities for others.",
    "protects the team from unnecessary interruptions and churn.",
    "helps define standards that improve the entire codebase.",
    "understands the bigger picture beyond individual tickets.",
    "consistently delivers on high‑impact, cross‑team initiatives.",
    "models ownership by caring deeply about outcomes.",
    "is comfortable saying “I don’t know” and learning publicly.",
    "helps align product, design, and engineering perspectives.",
    "nurtures future leaders through trust and thoughtful guidance.",
    "navigates disagreements with curiosity and respect.",
    "uplifts quieter voices and ensures they are heard.",
    "encourages experimentation while managing risk responsibly.",
    "keeps documentation and knowledge flowing across the team.",
    "invests time in refactoring to prevent future pain.",
    "helps simplify processes that have become too complex.",
    "is a dependable partner to stakeholders and peers.",
    "consistently raises the technical bar in a supportive way.",
    "uses their experience to create clarity during uncertainty.",
    "helps teams celebrate progress, not just milestones.",
];

pub const VETERAN: [&str; 40] = [
    "{username}’s years of experience bring depth, wisdom, and perspective.",
    "has seen many technologies come and go and adapts with intention.",
    "understands that fundamentals outlast any single framework.",
    "recognizes patterns quickly from a wealth of past experience.",
    "knows when history is repeating itself and guides accordingly.",
    "balances innovation with proven, battle‑tested practices.",
    "stays curious, even after many years in the industry.",
    "chooses tools thoughtfully, not just because they are new.",
    "understands the human side of software as deeply as the technical side.",
    "brings calm and stability to high‑pressure situations.",
    "helps younger engineers avoid common long‑term pitfalls.",
    "has learned that clear communication is as powerful as code.",
    "knows that maintainability is a gift to future teams.",
    "uses experience to simplify, not overcomplicate.",
    "has grown through many failures and learned from each one.",
    "understands that sustainable systems outlive individual trends.",
    "mentors across generations of engineers with generosity.",
    "recognizes when process helps and when it hinders.",
    "respects legacy systems while guiding their evolution.",
    "has built a strong intuition for what will scale over time.",
    "has seen architecture decisions play out over many years.",
    "understands that healthy teams build healthy software.",
    "uses perspective to keep short‑term issues in context.",
    "knows that careers are marathons, not sprints.",
    "has proven they can keep learning across multiple eras of tech.",
    "is comfortable letting go of outdated ideas and adopting better ones.",
    "helps organizations avoid repeating past mistakes.",
    "understands the value of clear boundaries and focus.",
    "sees the long‑term impact behind everyday technical choices.",
    "recognizes that mentoring is one of their highest‑leverage skills.",
    "gracefully adapts workflows to match changing realities.",
    "has developed a deep sense of technical judgment over time.",
    "knows that excellence includes kindness and patience.",
    "uses experience to protect teams from unnecessary burnout.",
    "understands that good software ultimately serves real people.",
    "is proof that a long career in tech can remain meaningful and joyful.",
    "leverages decades of learning to make better, calmer decisions.",
    "knows when to push for change and when to preserve stability.",
    "inspires others by showing that growth never has to stop.",
    "carries the history of many systems and still welcomes what’s next.",
];
pub const LONGDAY: [&str; 40] = [
    "has already put in a tremendous amount of focused effort today.",
    "is allowed to feel tired after working hard for so many hours.",
    "can pause, breathe, and choose the next step with intention.",
    "has already created value today, even if it doesn’t all show yet.",
    "is allowed to take breaks without feeling guilty.",
    "can end the day without finishing everything on the list.",
    "has done enough for today; progress matters more than perfection.",
    "can trust that a rested mind will solve problems more easily tomorrow.",
    "has the right to log off and recharge, even on intense days.",
    "is not defined by productivity in a single long workday.",
    "can acknowledge their effort instead of only seeing what’s left.",
    "has handled many hard days before and made it through.",
    "can choose to wrap up and leave some tasks for another day.",
    "is allowed to prioritize wellbeing over squeezing in one more task.",
    "has already demonstrated commitment and resilience today.",
    "can celebrate small wins from this long work session.",
    "is allowed to say “this is enough for today” and mean it.",
    "can step away knowing that unfinished work does not equal failure.",
    "deserves rest as much as they deserve success.",
    "can switch from “pushing harder” to “taking care of myself now.”",
    "knows that overworking today can reduce effectiveness tomorrow.",
    "has done meaningful work, even if it felt messy at times.",
    "is allowed to close the laptop and return with fresh energy later.",
    "can accept that tired code is rarely the best code.",
    "has earned a moment to reflect, stretch, and decompress.",
    "is not obligated to be available every minute of a long day.",
    "can trust their future self to handle what remains.",
    "can choose rest as a valid, productive next action.",
    "has the strength to set boundaries around their time.",
    "can recognize that today’s effort moves long‑term goals forward.",
    "is allowed to slow down when their brain feels overloaded.",
    "can leave work unfinished without losing professionalism.",
    "has already proven their reliability through consistent effort.",
    "can feel proud of showing up and staying engaged for so long.",
    "knows that self‑care is part of being an effective engineer.",
    "is allowed to log off without justifying every unfinished task.",
    "can give themselves credit for the invisible mental work they did.",
    "is allowed to feel both tired and accomplished at the same time.",
    "can end this long workday with gratitude for their own effort.",
    "deserves rest, recovery, and something that brings them joy after work.",
];

pub const NVIM: [&str; 30] = [
    "navigates code in nvim/vim with speed and precision.",
    "turns modal editing into a superpower for deep focus.",
    "proves that mastering nvim/vim is a long‑term investment in efficiency.",
    "uses keyboard‑only workflows to stay in the coding flow.",
    "remembers that it was okay for nvim/vim to feel confusing at first.",
    "continues to discover new motions and commands that boost productivity.",
    "uses custom keymaps to shape nvim/vim around their own workflow.",
    "is allowed to keep their config simple while they learn.",
    "knows that even a small improvement in their vimrc/init.lua compounds over time.",
    "treats their nvim/vim setup as a living, evolving tool.",
    "trusts their muscle memory to carry them through complex edits.",
    "is not required to know every command to be effective in nvim/vim.",
    "is allowed to look up motions, commands, and mappings as needed.",
    "uses splits, buffers, and tabs in nvim/vim to manage complexity calmly.",
    "can build a personalized IDE experience entirely inside nvim.",
    "remembers that quitting nvim/vim once felt impossible and now feels trivial.",
    "sees their growing comfort with nvim/vim as proof of steady learning.",
    "chooses plugins thoughtfully to support, not distract from, their work.",
    "knows that a lean, well‑understood config beats a bloated one.",
    "can adjust their nvim/vim setup one small improvement at a time.",
    "embraces that mastery in nvim/vim comes from repetition, not perfection.",
    "appreciates how nvim/vim keeps their hands on the keyboard and mind in the code.",
    "uses macros and registers to eliminate repetitive editing.",
    "can navigate large files in nvim/vim with confidence and ease.",
    "recognizes that knowing hjkl is just the beginning of their journey.",
    "knows they can always refactor their config as their needs evolve.",
    "proves that powerful tooling does not have to be heavy or graphical.",
    "uses nvim/vim as a reminder that minimalism can be incredibly powerful.",
    "is building a setup in nvim/vim that truly feels like home.",
    "shows that investing in editor mastery pays off every single day.",
];

pub const SWAYWM: [&str; 30] = [
    "uses swaywm to create a focused, distraction‑free workspace.",
    "turns tiling window management into a calm, intentional workflow.",
    "designs a swaywm layout that keeps tools exactly where they are needed.",
    "proves that keyboard‑driven window management boosts deep work.",
    "is allowed to keep swaywm configs simple while still being powerful.",
    "customizes swaywm step by step, turning it into a personal command center.",
    "uses workspaces in swaywm to separate contexts and reduce mental clutter.",
    "appreciates how swaywm helps them stay organized across many windows.",
    "leverages swaywm shortcuts to switch tasks quickly and smoothly.",
    "treats their swaywm configuration as code that can be refined over time.",
    "understands that learning swaywm is an investment in long‑term efficiency.",
    "finds satisfaction in a clean, tiling layout that supports their focus.",
    "uses swaywm to keep terminals, editors, and browsers all within easy reach.",
    "embraces the flexibility of swaywm to match their own mental model.",
    "knows that every new keybinding in swaywm saves time in the future.",
    "is allowed to experiment with layouts until their setup feels just right.",
    "uses swaywm to minimize window dragging and maximize flow.",
    "combines swaywm with their tools to build a highly efficient dev environment.",
    "recognizes that a well‑tuned swaywm setup reduces cognitive overhead.",
    "is confident moving between projects using swaywm’s powerful workspaces.",
    "understands that they don’t need a flashy desktop to be productive.",
    "chooses swaywm because it aligns with their preference for simplicity and control.",
    "refines their swaywm config like any other long‑lived piece of code.",
    "knows that mastering swaywm is a gradual, rewarding process.",
    "uses swaywm to keep their environment consistent across reboots and sessions.",
    "appreciates how swaywm keeps them close to the shell and the keyboard.",
    "is not required to have a perfect config; progress is enough.",
    "uses swaywm to make multitasking feel deliberate instead of chaotic.",
    "shows that a thoughtful window manager can amplify engineering focus.",
    "continues to shape swaywm into a workspace that fully supports their best work.",
];
